### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by ly469097645** [Zhaoss/WeiXinRecordedDemo#12]
VCamera.initialize(this);这句话一调用就报jni错误

java.lang.UnsatisfiedLinkError: No implementation found for void com.mitaodate.video.camera.adapter.UtilityAdapter.FFmpegInit(java.lang.Object, java.lang.String) (tried Java_com_mitaodate_video_camera_adapter_UtilityAdapter_FFmpegInit and Java_com_mitaodate_video_camera_adapter_UtilityAdapter_FFmpegInit__Ljava_lang_Object_2Ljava_lang_String_2)

**Comment by Zhaoss** [comment]
https://github.com/Zhaoss/WeiXinRecordedDemo/issues/6#issuecomment-285246742

**Comment by ly469097645** [comment]
我新建了一个什么都没有的空白项目，然后将demo里的内容拷贝过来运行，同样报错咋办，求救

**Comment by ly469097645** [comment]
我新建了一个什么都没有的项目，把代码拷贝过去还是有错误

**Comment by ly469097645** [comment]
.mitaodate E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.mitaodate, PID: 20130
                                                               java.lang.UnsatisfiedLinkError: No implementation found for void com.mitaodate.yixia.videoeditor.adapter.UtilityAdapter.FFmpegInit(java.lang.Object, java.lang.String) (tried Java_com_mitaodate_yixia_videoeditor_adapter_UtilityAdapter_FFmpegInit and Java_com_mitaodate_yixia_videoeditor_adapter_UtilityAdapter_FFmpegInit__Ljava_lang_Object_2Ljava_lang_String_2)
                                                                   at com.mitaodate.yixia.videoeditor.adapter.UtilityAdapter.FFmpegInit(Native Method)
                                                                   at com.mitaodate.yixia.camera.VCamera.initialize(VCamera.java:51)
                                                                   at com.mitaodate.app.MyApplication.onCreate(MyApplication.java:52)
                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4726)
                                                                   at android.app.ActivityThread.access$1600(ActivityThread.java:153)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1412)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5438)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by ly469097645** [comment]
我已经把项目里其他的arm文件都删了只留下armv7的，怎么还是无法初始化

**Comment by Zhaoss** [comment]
自己查看一下包名  所有包名路径不要改

**Comment by Zhaoss** [comment]
你运行一下我的代码 如果我的代码没问题 那就是那面有不对的地方, 一个个对着改

**Comment by Zhaoss** [comment]
你运行一下我的代码 如果我的代码没问题 那就是你那面有不对的地方, 一个个对着改

**Comment by ly469097645** [comment]
是包名的问题。。感谢

**Comment by liangjiaxuan** [comment]
请问一下这里说的包名的问题能说具体点吗？感谢

**Comment by liangjiaxuan** [comment]
No implementation found for void com.rongwei.weixinrecordeddemo.yixia.videoeditor.adapter.UtilityAdapter.FFmpegInit(java.lang.Object, java.lang.String) (tried Java_com_rongwei_weixinrecordeddemo_yixia_videoeditor_adapter_UtilityAdapter_FFmpegInit and Java_com_rongwei_weixinrecordeddemo_yixia_videoeditor_adapter_UtilityAdapter_FFmpegInit__Ljava_lang_Object_2Ljava_lang_String_2)
