### ISSUE TITLE
锤子手机后置摄像头 黑屏

### ISSUE THREAD

**Issue by wxh12138** [Zhaoss/WeiXinRecordedDemo#45]
附上报错信息
```
01-18 18:15:48.573 946-1535/? E/ActivityManager: setAppStartingWindow app stack
01-18 18:15:48.603 13397-13397/com.mvideo.record E/YXLog: action_action 4 start 
01-18 18:15:48.603 13397-13397/com.mvideo.record E/YXLog: ffmpeg kill
01-18 18:15:48.633 13397-13397/com.mvideo.record E/YXLog: action_action 4 finish 0
01-18 18:15:48.633 13397-13397/com.mvideo.record E/YXLog: action_action 0 start 
01-18 18:15:48.633 13397-13397/com.mvideo.record E/YXLog: action_action 0 finish 0
01-18 18:15:48.693 13397-13397/com.mvideo.record E/Camera: Camera open package is com.mvideo.record

01-18 18:15:48.863 29816-14220/? E/QCameraParameters: int32_t qcamera::QCameraParameters::setPreviewFpsRange(const qcamera::QCameraParameters&): error: FPS range value not supported
01-18 18:15:48.863 13397-13397/com.mvideo.record W/System.err: java.lang.RuntimeException: setParameters failed
01-18 18:15:48.863 13397-13397/com.mvideo.record W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
01-18 18:15:48.873 13397-13397/com.mvideo.record W/System.err:     at android.hardware.Camera.setParameters(Camera.java:2024)
01-18 18:15:48.873 13397-13397/com.mvideo.record W/System.err:     at com.yixia.camera.MediaRecorderBase.startPreview(MediaRecorderBase.java:546)
01-18 18:15:48.873 13397-13397/com.mvideo.record W/System.err:     at com.yixia.camera.MediaRecorderBase.surfaceCreated(MediaRecorderBase.java:629)
```

**Comment by Zhaoss** [comment]
是录制的时候是黑屏 还是预览就黑屏了 看日志是fps的问题 试着调低看看

**Comment by Zhaoss** [comment]
MediaRecorderBase类里 mParameters.setPreviewFpsRange() 这是设置fps的方法 你自己调一下

**Comment by wxh12138** [comment]
试了一下，不是这个地方的问题,我把全部的错误信息都发上来
```
01-19 09:16:54.973 14736-14736/? D/dalvikvm: Late-enabling CheckJNI
01-19 09:16:55.053 14736-14736/com.example.zhaoshuang.weixinrecordeddemo D/dalvikvm: Trying to load lib /data/app-lib/com.example.zhaoshuang.weixinrecordeddemo-1/libutility.so 0x424c6d10
01-19 09:16:55.053 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/linker: libutility.so has text relocations. This is wasting memory and is a security risk. Please fix.
01-19 09:16:55.063 14736-14736/com.example.zhaoshuang.weixinrecordeddemo D/dalvikvm: Added shared lib /data/app-lib/com.example.zhaoshuang.weixinrecordeddemo-1/libutility.so 0x424c6d10
01-19 09:16:55.063 14736-14736/com.example.zhaoshuang.weixinrecordeddemo I/[VCamera]: Application package name: com.example.zhaoshuang.weixinrecordeddemo
01-19 09:16:55.063 14736-14736/com.example.zhaoshuang.weixinrecordeddemo I/[VCamera]: Copyright (c) YIXIA (http://miaopai.yixia.com)
01-19 09:16:55.073 14736-14736/com.example.zhaoshuang.weixinrecordeddemo I/dalvikvm: Could not find method android.widget.ProgressBar.setIndeterminateTintList, referenced from method com.example.zhaoshuang.weixinrecordeddemo.BaseActivity.showProgressDialog
01-19 09:16:55.073 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/dalvikvm: VFY: unable to resolve virtual method 17405: Landroid/widget/ProgressBar;.setIndeterminateTintList (Landroid/content/res/ColorStateList;)V
01-19 09:16:55.073 14736-14736/com.example.zhaoshuang.weixinrecordeddemo D/dalvikvm: VFY: replacing opcode 0x6e at 0x0033
01-19 09:16:55.113 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/YXLog: action_action 4 start 
01-19 09:16:55.113 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/YXLog: action_action 4 finish 0
01-19 09:16:55.113 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/YXLog: action_action 0 start 
01-19 09:16:55.123 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/YXLog: action_action 0 finish 0
01-19 09:16:55.193 14736-14736/com.example.zhaoshuang.weixinrecordeddemo I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LNX.LA.3.5.1.5.04.04.02.076.008_msm8974_LNX.LA.3.5.1.5__release_AU ()
                                                                                       OpenGL ES Shader Compiler Version: E031.24.00.09
                                                                                       Build Date: 06/12/14 Thu
                                                                                       Local Branch: mybranch3550557
                                                                                       Remote Branch: quic/LNX.LA.3.5.1.5
                                                                                       Local Patches: NONE
                                                                                       Reconstruct Branch: AU_LINUX_ANDROID_LNX.LA.3.5.1.5.04.04.02.076.008 +  NOTHING
01-19 09:16:55.223 14736-14736/com.example.zhaoshuang.weixinrecordeddemo D/OpenGLRenderer: Enabling debug mode 0
01-19 09:16:55.243 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/Camera: Camera open package is com.example.zhaoshuang.weixinrecordeddemo
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err: java.lang.RuntimeException: setParameters failed
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.hardware.Camera.native_setParameters(Native Method)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.hardware.Camera.setParameters(Camera.java:2024)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.yixia.camera.MediaRecorderBase.startPreview(MediaRecorderBase.java:542)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.yixia.camera.MediaRecorderBase.surfaceCreated(MediaRecorderBase.java:625)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView.updateWindow(SurfaceView.java:572)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView.access$000(SurfaceView.java:86)
01-19 09:16:55.423 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:175)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:872)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2010)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1106)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5851)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:574)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer.doFrame(Choreographer.java:544)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:733)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.os.Looper.loop(Looper.java:136)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5110)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo W/System.err:     at dalvik.system.NativeStart.main(Native Method)
01-19 09:16:55.433 14736-14736/com.example.zhaoshuang.weixinrecordeddemo E/Yixia: startPreview fail :setParameters failed
```
