### ISSUE TITLE
No implementation found for int com.lansosdk.videoeditor.MediaInfo.nativePrepare(java.lang.String, boolean)

### ISSUE THREAD

**Issue by anonym2** [Zhaoss/WeiXinRecordedDemo#88]
Process: com.zhaoss.weixinrecordeddemo, PID: 26732
    java.lang.UnsatisfiedLinkError: No implementation found for int com.lansosdk.videoeditor.MediaInfo.nativePrepare(java.lang.String, boolean) (tried Java_com_lansosdk_videoeditor_MediaInfo_nativePrepare and Java_com_lansosdk_videoeditor_MediaInfo_nativePrepare__Ljava_lang_String_2Z)
        at com.lansosdk.videoeditor.MediaInfo.nativePrepare(Native Method)
        at com.lansosdk.videoeditor.MediaInfo.prepare(MediaInfo.java:230)
        at com.zhaoss.weixinrecorded.activity.EditVideoActivity.initVideoSize(EditVideoActivity.java:353)
        at com.zhaoss.weixinrecorded.activity.EditVideoActivity.onCreate(EditVideoActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Activity.performCreate(Activity.java:7014)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2760)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2885)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1615)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by Zhaoss** [comment]
看看lansosdk初始化是否成功

**Comment by lpwyz** [comment]
> 看看lansosdk初始化是否成功

您好，这个我完全copy您的那个 weixinrecorded 然后我导入，在然后选择了视频，传递地址，跳转到，EditVideoActivity 然后也爆这个错误了：

java.lang.UnsatisfiedLinkError: No implementation found for int com.lansosdk.videoeditor.MediaInfo.nativePrepare(java.lang.String, boolean) (tried Java_com_lansosdk_videoeditor_MediaInfo_nativePrepare and Java_com_lansosdk_videoeditor_MediaInfo_nativePrepare__Ljava_lang_String_2Z)
        at com.lansosdk.videoeditor.MediaInfo.nativePrepare(Native Method)
        at com.lansosdk.videoeditor.MediaInfo.prepare(MediaInfo.java:230)
        at com.zhaoss.weixinrecorded.activity.EditVideoActivity.initVideoSize(EditVideoActivity.java:357)
        at com.zhaoss.weixinrecorded.activity.EditVideoActivity.onCreate(EditVideoActivity.java:125)
        at android.app.Activity.performCreate(Activity.java:8491)
        at android.app.Activity.performCreate(Activity.java:8469)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4089)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8344)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1065)

**Comment by lpwyz** [comment]
> 看看lansosdk初始化是否成功

这个咋看啊，不就是 直接导入weixinrecorded 模块， 然后 把视频地址 传递给 EditVideoActivity 就可以了吗
