### ISSUE TITLE
魅族mx5录制视频崩溃

### ISSUE THREAD

**Issue by lixiaoly** [Zhaoss/WeiXinRecordedDemo#99]

**Comment by lixiaoly** [comment]
android.media.MediaCodec$CodecException: Error 0x80001001
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:590)
        at com.zhaoss.weixinrecorded.util.AvcEncoder.<init>(AvcEncoder.java:48)

**Comment by Zhaoss** [comment]
编码器有问题, 联发科处理器的事情吧 机型有点老了
